version: '3.8'

services:
  # ChainContext API
  api:
    # Using the exact image that matches the contract's expected digest
    image: a490f5528c87   # This is the image that matches the contract's expected digest
    # Commenting out the build section since we're using a pre-built image
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/chaincontext
      - REDIS_URI=redis://redis:6379/0
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - WEB3_PROVIDER_URI=${WEB3_PROVIDER_URI:-https://flare-api.flare.network/ext/C/rpc}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - FLARE_VTPM_ATTESTATION_ADDRESS=${FLARE_VTPM_ATTESTATION_ADDRESS:-0x93012953008ef9AbcB71F48C340166E8f384e985}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      - mongo
      - redis
      - qdrant
    devices:
      - /dev/tpm0:/dev/tpm0
    restart: unless-stopped

  # MongoDB
  mongo:
    image: mongo:5.0
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

  # Redis
  redis:
    image: redis:7.0
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
    restart: unless-stopped

volumes:
  mongo_data:
  redis_data:
  qdrant_data:
